# Generated by Django 5.2.7 on 2025-11-21 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('cultivoid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cultivo',
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('estadosolicitudid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estadosolicitud',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('proveedorid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rolid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('solicitudid', models.AutoField(primary_key=True, serialize=False)),
                ('fechasolicitud', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'solicitud',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('insumoid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('proveedor', models.ForeignKey(db_column='proveedorid', on_delete=django.db.models.deletion.CASCADE, to='api.proveedor')),
            ],
            options={
                'db_table': 'insumo',
            },
        ),
        migrations.CreateModel(
            name='ComprobanteEntrega',
            fields=[
                ('comprobanteid', models.AutoField(primary_key=True, serialize=False)),
                ('fechaentrega', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('entregadopor', models.IntegerField()),
                ('recibidopor', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('solicitud', models.ForeignKey(db_column='solicitudid', on_delete=django.db.models.deletion.CASCADE, to='api.solicitud')),
            ],
            options={
                'db_table': 'comprobanteentrega',
            },
        ),
        migrations.CreateModel(
            name='SolicitudDetalle',
            fields=[
                ('solicituddetalleid', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('preciounitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('insumo', models.ForeignKey(db_column='insumoid', on_delete=django.db.models.deletion.CASCADE, to='api.insumo')),
                ('solicitud', models.ForeignKey(db_column='solicitudid', on_delete=django.db.models.deletion.CASCADE, to='api.solicitud')),
            ],
            options={
                'db_table': 'solicituddetalle',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuarioid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('passwordhash', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(db_column='rolid', on_delete=django.db.models.deletion.PROTECT, to='api.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(db_column='usuarioid', on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pagoid', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_pago', models.CharField(default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('solicitud', models.ForeignKey(db_column='solicitudid', on_delete=django.db.models.deletion.CASCADE, to='api.solicitud')),
                ('usuario', models.ForeignKey(db_column='usuarioid', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoSolicitud',
            fields=[
                ('historialid', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estadosolicitud', models.ForeignKey(db_column='estadosolicitudid', on_delete=django.db.models.deletion.CASCADE, to='api.estadosolicitud')),
                ('solicitud', models.ForeignKey(db_column='solicitudid', on_delete=django.db.models.deletion.CASCADE, to='api.solicitud')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuarioid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuario')),
            ],
            options={
                'db_table': 'historialestadosolicitud',
            },
        ),
        migrations.CreateModel(
            name='UsuarioCultivo',
            fields=[
                ('usuariocultivoid', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('fechasiembra', models.DateField()),
                ('cultivoid', models.ForeignKey(db_column='cultivoid', on_delete=django.db.models.deletion.CASCADE, to='api.cultivo')),
                ('usuarioid', models.ForeignKey(db_column='usuarioid', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'usuariocultivo',
            },
        ),
        migrations.CreateModel(
            name='HistorialCultivo',
            fields=[
                ('historialid', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(db_column='usuarioid', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
                ('usuariocultivo', models.ForeignKey(db_column='usuariocultivoid', on_delete=django.db.models.deletion.CASCADE, to='api.usuariocultivo')),
            ],
            options={
                'db_table': 'historialcultivo',
            },
        ),
    ]
